//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automobile
    {
        public int id { get; set; }
        public string model { get; set; }
        public Nullable<int> enginePower { get; set; }
        public Nullable<int> maxSpeed { get; set; }
        public Nullable<decimal> acceleration { get; set; }
        public Nullable<decimal> fuelEconomy { get; set; }
        public Nullable<decimal> price { get; set; }
        public int vendorId { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
