//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string E_mail { get; set; }
        public string Phone { get; set; }
        public string HouseID { get; set; }
        public Nullable<int> SolvedBy { get; set; }
        public Nullable<bool> Solved { get; set; }
        public string UserText { get; set; }
    
        public virtual House House { get; set; }
    }
}
