USE [master]
GO

/****** Object:  Database [liltarp]    Script Date: 12/5/2013 10:10:51 ******/
CREATE DATABASE [liltarp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'liltarp', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\liltarp.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'liltarp_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\liltarp_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [liltarp] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [liltarp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [liltarp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [liltarp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [liltarp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [liltarp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [liltarp] SET ARITHABORT OFF 
GO

ALTER DATABASE [liltarp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [liltarp] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [liltarp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [liltarp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [liltarp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [liltarp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [liltarp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [liltarp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [liltarp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [liltarp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [liltarp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [liltarp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [liltarp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [liltarp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [liltarp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [liltarp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [liltarp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [liltarp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [liltarp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [liltarp] SET  MULTI_USER 
GO

ALTER DATABASE [liltarp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [liltarp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [liltarp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [liltarp] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [liltarp] SET  READ_WRITE 
GO

