<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Nybyggeri.aspx.cs" Inherits="Application.Static_page.Nybyggeri" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1 style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 36px; font-family: Dosis, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-weight: 300; line-height: 1.1; text-shadow: rgba(0, 0, 0, 0.298039) -1px -1px 0px; color: rgb(238, 238, 238); font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">Nybyggeri<span class="Apple-converted-space">&nbsp;</span><small style="box-sizing: border-box; font-size: 24px; font-weight: normal; line-height: 1; color: rgb(122, 130, 136);">- Høj fleksibilitet</small></h1>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(238, 238, 238); font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        N. P. Liltarp ApS har en meget høj grad af fleksibilitet.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(238, 238, 238); font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        På det håndværksmæssige område har vi et godt og fast- tømret samarbejde med under- entreprenører, som matcher os kvalitetsmæssigt og med hensyn til overholdelse af aftaler m.m.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(238, 238, 238); font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        Også indenfor projektering træk- ker vi på eksterne firmaer. Vi laver selv en del tegnestue- arbejde, men ved større projekter samarbejder vi med arkitekt- og ingeniørfirmaer.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(238, 238, 238); font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        N. P. Liltarp løser totalprojekter for erhvervslivet, hvor vi er med helt fra starten, hvor vi kommer med idéer og skitseforslag til byggeriet.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(238, 238, 238); font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        Vi sørger selvfølgelig for ansøgninger og byggetilladelser m.m., og efterfølgende styrer vi med sikker hånd koordineringen mellem de forskellige leveran- dører og håndværksfirmaer.</p>
</asp:Content>
