<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Ombygning.aspx.cs" Inherits="Application.Static_page.Ombygning" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1 style="box-sizing: border-box; margin: 0px 0px 10px; font-size: 36px; font-family: Dosis, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-weight: 300; line-height: 1.1; text-shadow: rgba(0, 0, 0, 0.298039) -1px -1px 0px; color: rgb(238, 238, 238); font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">Ombygning</h1>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(238, 238, 238); font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        Man skal have et godt øje for, hvad der &quot;klæ&#39;r&quot; en bygning, når man bygger om eller laver en tilbygning.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(238, 238, 238); font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        Det har tømrermester Peder Liltarp, der indenfor både erhvervslivet og privatlivet, har stået for en lang række flotte renoveringer af ældre huse.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(238, 238, 238); font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        Her mærkes også et markant større krav om kvalitet, hvad angår både materialer og udførelse, men også når det gælder udseendet - såvel ude som inde. Vi tager først en drøftelse med kunden, hvor vi grundigt vurderer stedet og den eksisterende bygning.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(238, 238, 238); font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        Derefter laver vi forslag med prisoverslag, så kunden ved hvad han får inden byggeriet går i gang.</p>
    <p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(238, 238, 238); font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 20px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        Her kommer vore store erfaring kunden til gode, så alt foregår med fagmandens ekspertise.</p>
</asp:Content>
